//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceStack.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceStack.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 错误的颜色二进制格式。 的本地化字符串。
        /// </summary>
        internal static string TextInvalidColorHex {
            get {
                return ResourceManager.GetString("TextInvalidColorHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的电子邮件格式。 的本地化字符串。
        /// </summary>
        internal static string TextInvalidEmail {
            get {
                return ResourceManager.GetString("TextInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的格式。 的本地化字符串。
        /// </summary>
        internal static string TextInvalidFormat {
            get {
                return ResourceManager.GetString("TextInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的手机号码格式。 的本地化字符串。
        /// </summary>
        internal static string TextInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("TextInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空或零长度。 的本地化字符串。
        /// </summary>
        internal static string TextIsNullOrEmpty {
            get {
                return ResourceManager.GetString("TextIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前长度{0}大于最大长度{1}。 的本地化字符串。
        /// </summary>
        internal static string TextMaxLengthOutOfRange {
            get {
                return ResourceManager.GetString("TextMaxLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前长度{0}小于最小长度{1}。 的本地化字符串。
        /// </summary>
        internal static string TextMinLengthOutOfRange {
            get {
                return ResourceManager.GetString("TextMinLengthOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前值{0}与指定值{1}相等。 的本地化字符串。
        /// </summary>
        internal static string ValueIsEqual {
            get {
                return ResourceManager.GetString("ValueIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前值{0}与指定值{1}不相等。 的本地化字符串。
        /// </summary>
        internal static string ValueIsNotEqual {
            get {
                return ResourceManager.GetString("ValueIsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前值{0}小于最小值{1}。 的本地化字符串。
        /// </summary>
        internal static string ValueLowLimitOutOfRange {
            get {
                return ResourceManager.GetString("ValueLowLimitOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前值{0}大于最大值{1}。 的本地化字符串。
        /// </summary>
        internal static string ValueUpperLimitOutOfRange {
            get {
                return ResourceManager.GetString("ValueUpperLimitOutOfRange", resourceCulture);
            }
        }
    }
}
